export enum ButtonPayload {
  ELIGIBLE_ACCOUNTS = 'ELIGIBLE_ACCOUNTS',
  VIEW_ACCOUNT_DETAIL = 'VIEW_ACCOUNT_DETAIL.',
  CONFIRM_PROCESSING_ACCOUNT = 'CONFIRM_PROCESSING_ACCOUNT',
  TALK_TO_BANKER = 'TALK_TO_BANKER',
  SELECT_TERM = 'SELECT_TERM',
  VIEW_TERM = 'VIEW_TERM',
  ACCEPT_TERM = 'ACCEPT_TERM',
  CANCEL_TERM = 'CANCEL_TERM',
  VARIABLE_HOME_LOAN = 'VARIABLE_HOME_LOAN',
  FIXED_HOME_LOAN = 'FIXED_HOME_LOAN',
  SELECT_HOME_LOAN = 'SELECT_HOME_LOAN',
  NO_THANKS = 'NO_THANKS',
  VIEW_ALL_ACCOUNTS = 'VIEW_ALL_ACCOUNTS'
}

export enum LoanModOptions {
  FIX = 'Fix my interest rate',
  REFIX = 'Refix my interest rate',
  SPLIT = 'Split my home loan',
  YES = 'Yes',
  NO = `No, I'm rich`,
}

export enum LoanAmounts {
  TWENTY_THOUSAND = '$20,000',
  FIFTY_THOUSAND = '$50,000',
  ONE_HUNDRED_THOUSAND = '$100,000',
  ONE_HUNDRED_FIFTY_THOUSAND = '$100,000',
}


